Updated README.me
camunda-community-hub/DiscourseSentiment pull request #2
Opened 2021-05-27 19:37 UTC by celanthe

Added a README to the project

2021-05-27 19:52 UTC, davidgs requested changes
line 4: I would use another term than Query here. Maybe `service` or something similar?

line 8: Same comment.

2021-05-27 21:16 UTC, mary-grace commented
Could we also add a "TBD" section that would serve as a roadmap/upcoming features? That way folks know what they can expect in the future.

2021-06-01 16:44 UTC, celanthe commented
@mary-grace @davidgs Thank you for the feedback! I've made the suggested changes in the [latest commit](https://github.com/camunda-community-hub/DiscourseSentiment/pull/2/commits/9353574bf8d72742d4da5697c8420138b5a177bd).

2021-06-01 16:47 UTC, davidgs approved these changes

2021-06-01 16:47 UTC, merged